# Generated by Django 4.2.6 on 2023-12-09 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SomeDB',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='...', max_length=100, verbose_name='Имя')),
                ('second_name', models.CharField(default='...', max_length=100, verbose_name='Фамилия')),
            ],
        ),
    ]
