# Generated by Django 4.2.6 on 2023-12-20 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='somedb',
            name='content',
            field=models.CharField(default='...', max_length=5000, verbose_name='Контент'),
        ),
        migrations.AlterField(
            model_name='somedb',
            name='name',
            field=models.CharField(default='', max_length=100, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='somedb',
            name='second_name',
            field=models.CharField(default='', max_length=100, verbose_name='Фамилия'),
        ),
    ]
