# Generated by Django 4.2.6 on 2023-11-27 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='men',
            name='second_name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='men',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
