# Generated by Django 4.2.6 on 2023-12-07 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='state',
            field=models.BooleanField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='descr',
            field=models.CharField(blank=True, default='...', max_length=100),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('sw', 'switch'), ('r', 'router'), ('cam', 'camera'), ('un', 'unknown')], default='un', max_length=6),
        ),
    ]
