# Generated by Django 4.2.6 on 2023-12-05 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='equipment',
            name='type',
        ),
        migrations.AddField(
            model_name='equipment',
            name='state',
            field=models.BooleanField(choices=[(0, 'Off'), (1, 'On')], default=0),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='descr',
            field=models.CharField(blank=True, default='...', max_length=100),
        ),
    ]
