# Generated by Django 4.2.6 on 2023-12-05 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_remove_equipment_type_equipment_state_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('sw', 'switch'), ('r', 'router'), ('cam', 'camera'), ('un', 'unknow')], default='un', max_length=6),
        ),
    ]
