# Generated by Django 4.2.6 on 2023-10-28 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_alter_maindb_age'),
    ]

    operations = [
        migrations.AddField(
            model_name='maindb',
            name='slug',
            field=models.SlugField(default=0, max_length=255),
        ),
    ]
