# Generated by Django 4.2.6 on 2023-12-09 06:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0002_equipment_state_alter_equipment_descr_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='descr',
            field=models.CharField(blank=True, default='...', max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='state',
            field=models.BooleanField(choices=[(0, 'Off'), (1, 'On')], default=0, verbose_name='Состояние'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('sw', 'switch'), ('r', 'router'), ('cam', 'camera'), ('un', 'unknown')], default='un', max_length=6, verbose_name='Тип оборудования'),
        ),
    ]
