# Generated by Django 4.2.6 on 2023-10-28 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_maindb_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maindb',
            name='slug',
            field=models.SlugField(max_length=255, unique=True),
        ),
    ]
