# Generated by Django 4.2.6 on 2023-12-06 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0003_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('switch', 'Switch'), ('router', 'Router'), ('camera', 'Camera'), ('unknow', 'Unknow')], default='unknow', max_length=6),
        ),
    ]
