# Generated by Django 4.2.6 on 2023-12-06 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('firstapp', '0004_alter_equipment_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='type',
            field=models.CharField(choices=[('sw', 'switch'), ('r', 'router'), ('cam', 'camera'), ('un', 'unknow')], default='un', max_length=6),
        ),
    ]
